[package]
name = "viendesu-http"
version = "0.1.0"
edition = "2024"

[features]
default = []
server = [
    "format-serde",
    "dep:axum",
    "dep:tower-http",
    "dep:serde_urlencoded",
    "dep:form_urlencoded",
    "dep:fastrace",
    "eva/tokio",
    "tokio/net",
    "dep:fastrace-axum"
]
format-serde = ["dep:serde_json", "dep:serde_path_to_error", "dep:rmp-serde", "dep:rmp"]

[dependencies]
viendesu-core.workspace = true
viendesu-protocol.workspace = true
http = "1.3.1"

serde.workspace = true
schemars.workspace = true
serde_json = { workspace = true, optional = true, features = ["raw_value"] }
futures.workspace = true

eva.workspace = true
eyre.workspace = true

axum = { optional = true, version = "0.8.4", default-features = false, features = ["http2", "ws", "macros", "multipart"] }
tower-http = { optional = true, version = "0.6.6", default-features = false, features = ["cors"] }
serde_urlencoded = { version = "0.7.1", optional = true }
serde_path_to_error = { version = "0.1", optional = true }
form_urlencoded = { version = "1", optional = true }

rmp-serde = { version = "1.3", optional = true }
rmp = { version = "0.8.14", optional = true }

tokio = { workspace = true, optional = true }

fastrace = { optional = true, version = "0.7.9" }
fastrace-axum = { optional = true, version = "0.1.3" }

[dev-dependencies]
viendesu-http = { path = ".", features = ["server"] }
tokio = { workspace = true, features = ["macros", "rt"] }
tower = { version = "0.5", features = ["util"] }
http-body-util = "0.1"
serde_json.workspace = true
rmp-serde = "1.3"
