[package]
name = "viendesu-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
viendesu-core.workspace = true
viendesu-protocol.workspace = true

eva.workspace = true
serde.workspace = true
serde_json.workspace = true

axum.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
tower = { workspace = true, features = ["util"] }
http-body-util.workspace = true
